sudo: required
services:
  - docker

before_install:
  - docker build -t mrjavad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrjavad/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-031589609724'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY